config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  resources :followers
  resources :images
  resources :comments
  resources :posts
  resources :users

  get '/search_suggestions', to: 'posts#search_suggestions'
  get 'user_posts', to: 'users#user_posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :image
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :set_follower, only: [:show, :edit, :update, :destroy]

  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
  end

  # GET /followers/new
  def new
    @follower = Follower.new
  end

  # GET /followers/1/edit
  def edit
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(follower_params)

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render :show, status: :created, location: @follower }
      else
        format.html { render :new }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followers/1
  # PATCH/PUT /followers/1.json
  def update
    respond_to do |format|
      if @follower.update(follower_params)
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { render :show, status: :ok, location: @follower }
      else
        format.html { render :edit }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower.destroy
    respond_to do |format|
      format.html { redirect_to followers_url, notice: 'Follower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower
      @follower = Follower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follower_params
      params.require(:follower).permit(:name, :image_id)
    end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_for(follower) do |f| %>
  <% if follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% follower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image_id %>
    <%= f.text_field :image_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.name %></td>
        <td><%= follower.image %></td>
        <td><%= link_to 'Show', follower %></td>
        <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
        <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @follower.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @follower.image %>
</p>

<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>